package com.amar.android.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.amar.android.db.Idiom;

import com.amar.android.db.IdiomDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig idiomDaoConfig;

    private final IdiomDao idiomDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        idiomDaoConfig = daoConfigMap.get(IdiomDao.class).clone();
        idiomDaoConfig.initIdentityScope(type);

        idiomDao = new IdiomDao(idiomDaoConfig, this);

        registerDao(Idiom.class, idiomDao);
    }
    
    public void clear() {
        idiomDaoConfig.getIdentityScope().clear();
    }

    public IdiomDao getIdiomDao() {
        return idiomDao;
    }

}
