package com.amar.android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IDIOM.
 */
public class Idiom {

    private Long id;
    private String name;
    private String pingyin;
    private String description;
    private String from;
    private String example;
    private String shortname;

    public Idiom() {
    }

    public Idiom(Long id) {
        this.id = id;
    }

    public Idiom(Long id, String name, String pingyin, String description, String from, String example, String shortname) {
        this.id = id;
        this.name = name;
        this.pingyin = pingyin;
        this.description = description;
        this.from = from;
        this.example = example;
        this.shortname = shortname;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPingyin() {
        return pingyin;
    }

    public void setPingyin(String pingyin) {
        this.pingyin = pingyin;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getExample() {
        return example;
    }

    public void setExample(String example) {
        this.example = example;
    }

    public String getShortname() {
        return shortname;
    }

    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

}
